name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          cache-dependency-path: '**/pom.xml'

      - name: Install dependencies and build
        run: |
          cd backend
          ./mvnw clean install

      - name: Run tests
        run: |
          cd backend
          ./mvnw test

      - name: Deploy to Production (optional)
        run: |
          # Deploy commands, e.g., to AWS, Heroku, etc.
          echo "Deploy backend to production"
