name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.14.0'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run tests
        run: |
          cd frontend
          npm run test -- --watch=false --browsers=ChromeHeadlessCI

      - name: Build the project
        run: |
          cd frontend
          npm run build --prod

      - name: Deploy to Production (optional)
        run: |
          # Deploy commands, e.g., to Netlify, Firebase, etc.
          echo "Deploy frontend to production"
